<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="57" passed="0" failed="0" skipped="55">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-13T16:05:36 IST" name="Regression Suite" finished-at="2024-06-13T16:05:36 IST" duration-ms="184">
    <groups>
      <group name="negative">
        <method signature="AttendanceTest.TC_002_VerifyAttendanceWithoutCapturingImage()[pri:2, instance:Tests.AttendanceTest@232a7d73]" name="TC_002_VerifyAttendanceWithoutCapturingImage" class="Tests.AttendanceTest"/>
        <method signature="CallPlanTest.TC_005_Verify_Upload_Button_Without_Completing_Form()[pri:4, instance:Tests.CallPlanTest@4372b9b6]" name="TC_005_Verify_Upload_Button_Without_Completing_Form" class="Tests.CallPlanTest"/>
        <method signature="DownloadcallsTest.TC_003_VerifyDuplicateCallDownload()[pri:3, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_003_VerifyDuplicateCallDownload" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_004_VerifyInvalidTargetDownload()[pri:4, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_004_VerifyInvalidTargetDownload" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_006_VerifySubmitButtonWithoutAddingTarget()[pri:6, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_006_VerifySubmitButtonWithoutAddingTarget" class="Tests.DownloadcallsTest"/>
        <method signature="VisitorLoginTest.TC_002_VerifySubmitButtonWithoutEnteringFields()[pri:2, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_002_VerifySubmitButtonWithoutEnteringFields" class="Tests.VisitorLoginTest"/>
        <method signature="LoginTest.TC_002_Verify_Login_With_Invalid_Username()[pri:2, instance:Tests.LoginTest@63dd899]" name="TC_002_Verify_Login_With_Invalid_Username" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_003_Verify_Login_With_Invalid_Password()[pri:3, instance:Tests.LoginTest@63dd899]" name="TC_003_Verify_Login_With_Invalid_Password" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_004_Verify_Login_With_Invalid_Project()[pri:4, instance:Tests.LoginTest@63dd899]" name="TC_004_Verify_Login_With_Invalid_Project" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_005_Verify_Login_With_Invalid_Mobile_Number()[pri:5, instance:Tests.LoginTest@63dd899]" name="TC_005_Verify_Login_With_Invalid_Mobile_Number" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_006_Verify_Login_Without_Entering_Username()[pri:6, instance:Tests.LoginTest@63dd899]" name="TC_006_Verify_Login_Without_Entering_Username" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_007_Verify_Login_Without_Entering_Password()[pri:7, instance:Tests.LoginTest@63dd899]" name="TC_007_Verify_Login_Without_Entering_Password" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_008_Verify_Login_Without_Entering_Project()[pri:8, instance:Tests.LoginTest@63dd899]" name="TC_008_Verify_Login_Without_Entering_Project" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_009_Verify_Login_Without_Entering_Mobile_Number()[pri:9, instance:Tests.LoginTest@63dd899]" name="TC_009_Verify_Login_Without_Entering_Mobile_Number" class="Tests.LoginTest"/>
      </group> <!-- negative -->
      <group name="regression">
        <method signature="AttendanceTest.TC_001_VerifyAttendanceModuleDisplayed()[pri:1, instance:Tests.AttendanceTest@232a7d73]" name="TC_001_VerifyAttendanceModuleDisplayed" class="Tests.AttendanceTest"/>
        <method signature="AttendanceTest.TC_002_VerifyAttendanceWithoutCapturingImage()[pri:2, instance:Tests.AttendanceTest@232a7d73]" name="TC_002_VerifyAttendanceWithoutCapturingImage" class="Tests.AttendanceTest"/>
        <method signature="AttendanceTest.TC_003_VerifyAttendanceSubmission()[pri:3, instance:Tests.AttendanceTest@232a7d73]" name="TC_003_VerifyAttendanceSubmission" class="Tests.AttendanceTest"/>
        <method signature="AttendanceTest.TC_004_VerifyAttendanceRecordedInDatabase()[pri:4, instance:Tests.AttendanceTest@232a7d73]" name="TC_004_VerifyAttendanceRecordedInDatabase" class="Tests.AttendanceTest"/>
        <method signature="CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed()[pri:1, instance:Tests.CallPlanTest@4372b9b6]" name="TC_001_Verify_Call_Plan_Module_Displayed" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_002_Verify_Sync_Button_Functionality()[pri:2, instance:Tests.CallPlanTest@4372b9b6]" name="TC_002_Verify_Sync_Button_Functionality" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_003_Verify_5_Minute_Sync_Process()[pri:3, instance:Tests.CallPlanTest@4372b9b6]" name="TC_003_Verify_5_Minute_Sync_Process" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_005_Verify_Upload_Button_Without_Completing_Form()[pri:4, instance:Tests.CallPlanTest@4372b9b6]" name="TC_005_Verify_Upload_Button_Without_Completing_Form" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_009_Verify_Call_Upload()[pri:5, instance:Tests.CallPlanTest@4372b9b6]" name="TC_009_Verify_Call_Upload" class="Tests.CallPlanTest"/>
        <method signature="DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed()[pri:1, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_001_VerifyDownloadCallsModuleIsDisplayed" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_002_VerifyCallsAreDownloaded()[pri:2, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_002_VerifyCallsAreDownloaded" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_003_VerifyDuplicateCallDownload()[pri:3, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_003_VerifyDuplicateCallDownload" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_004_VerifyInvalidTargetDownload()[pri:4, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_004_VerifyInvalidTargetDownload" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_005_VerifyRemoveButtonFunctionality()[pri:5, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_005_VerifyRemoveButtonFunctionality" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_006_VerifySubmitButtonWithoutAddingTarget()[pri:6, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_006_VerifySubmitButtonWithoutAddingTarget" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_007_VerifyTargetIDTextboxCharacterLimit()[pri:7, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_007_VerifyTargetIDTextboxCharacterLimit" class="Tests.DownloadcallsTest"/>
        <method signature="ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed()[pri:1, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC_001_Verify_ResourceCenter_Module_Displayed" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC002_VerifyPPTXFileDownloaded()[pri:2, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC002_VerifyPPTXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC003_VerifyMP4FileDownloaded()[pri:3, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC003_VerifyMP4FileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC004_VerifyPDFFileDownloaded()[pri:4, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC004_VerifyPDFFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC005_VerifyDOCXFileDownloaded()[pri:5, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC005_VerifyDOCXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC006_VerifyJPGFileDownloaded()[pri:6, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC006_VerifyJPGFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC007_VerifyXLSXFileDownloaded()[pri:7, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC007_VerifyXLSXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed()[pri:1, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_001_VerifyVisitorLoginModuleDisplayed" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_002_VerifySubmitButtonWithoutEnteringFields()[pri:2, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_002_VerifySubmitButtonWithoutEnteringFields" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_003_VerifyVisitorEmpIDTextboxCharacterLimit()[pri:3, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_003_VerifyVisitorEmpIDTextboxCharacterLimit" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters()[pri:4, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers()[pri:5, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_006_VerifyVisitorNameTextboxCharacterLimit()[pri:6, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_006_VerifyVisitorNameTextboxCharacterLimit" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters()[pri:7, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_008_VerifyVisitorNameTextboxAcceptsNumbers()[pri:8, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_008_VerifyVisitorNameTextboxAcceptsNumbers" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_009_VerifyDesignationTextboxCharacterLimit()[pri:9, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_009_VerifyDesignationTextboxCharacterLimit" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters()[pri:10, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_011_VerifyDesignationTextboxAcceptsNumbers()[pri:11, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_011_VerifyDesignationTextboxAcceptsNumbers" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_012_VerifyRemarksTextboxCharacterLimit()[pri:12, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_012_VerifyRemarksTextboxCharacterLimit" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters()[pri:13, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_014_Verify_RemarksTextboxAcceptsNumbers()[pri:14, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_014_Verify_RemarksTextboxAcceptsNumbers" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_015_Verify_Visitor_Upload()[pri:15, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_015_Verify_Visitor_Upload" class="Tests.VisitorLoginTest"/>
        <method signature="LoginTest.TC_001_Verify_Login_With_Valid_Credentials()[pri:1, instance:Tests.LoginTest@63dd899]" name="TC_001_Verify_Login_With_Valid_Credentials" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_002_Verify_Login_With_Invalid_Username()[pri:2, instance:Tests.LoginTest@63dd899]" name="TC_002_Verify_Login_With_Invalid_Username" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_003_Verify_Login_With_Invalid_Password()[pri:3, instance:Tests.LoginTest@63dd899]" name="TC_003_Verify_Login_With_Invalid_Password" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_004_Verify_Login_With_Invalid_Project()[pri:4, instance:Tests.LoginTest@63dd899]" name="TC_004_Verify_Login_With_Invalid_Project" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_005_Verify_Login_With_Invalid_Mobile_Number()[pri:5, instance:Tests.LoginTest@63dd899]" name="TC_005_Verify_Login_With_Invalid_Mobile_Number" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_006_Verify_Login_Without_Entering_Username()[pri:6, instance:Tests.LoginTest@63dd899]" name="TC_006_Verify_Login_Without_Entering_Username" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_007_Verify_Login_Without_Entering_Password()[pri:7, instance:Tests.LoginTest@63dd899]" name="TC_007_Verify_Login_Without_Entering_Password" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_008_Verify_Login_Without_Entering_Project()[pri:8, instance:Tests.LoginTest@63dd899]" name="TC_008_Verify_Login_Without_Entering_Project" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_009_Verify_Login_Without_Entering_Mobile_Number()[pri:9, instance:Tests.LoginTest@63dd899]" name="TC_009_Verify_Login_Without_Entering_Mobile_Number" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_010_Verify_UsernameTextboxCharacterLimit()[pri:10, instance:Tests.LoginTest@63dd899]" name="TC_010_Verify_UsernameTextboxCharacterLimit" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters()[pri:11, instance:Tests.LoginTest@63dd899]" name="TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_012_Verify_UsernameTextboxAcceptsNumbers()[pri:12, instance:Tests.LoginTest@63dd899]" name="TC_012_Verify_UsernameTextboxAcceptsNumbers" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_013_Verify_PasswordTextboxCharacterLimit()[pri:13, instance:Tests.LoginTest@63dd899]" name="TC_013_Verify_PasswordTextboxCharacterLimit" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_014_Verify_ProjectTextboxCharacterLimit()[pri:14, instance:Tests.LoginTest@63dd899]" name="TC_014_Verify_ProjectTextboxCharacterLimit" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters()[pri:15, instance:Tests.LoginTest@63dd899]" name="TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_016_Verify_ProjectTextboxAcceptsNumbers()[pri:16, instance:Tests.LoginTest@63dd899]" name="TC_016_Verify_ProjectTextboxAcceptsNumbers" class="Tests.LoginTest"/>
        <method signature="LoginTest.TC_017_Verify_MobileNumberTextboxCharacterLimit()[pri:17, instance:Tests.LoginTest@63dd899]" name="TC_017_Verify_MobileNumberTextboxCharacterLimit" class="Tests.LoginTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="AttendanceTest.TC_001_VerifyAttendanceModuleDisplayed()[pri:1, instance:Tests.AttendanceTest@232a7d73]" name="TC_001_VerifyAttendanceModuleDisplayed" class="Tests.AttendanceTest"/>
        <method signature="AttendanceTest.TC_003_VerifyAttendanceSubmission()[pri:3, instance:Tests.AttendanceTest@232a7d73]" name="TC_003_VerifyAttendanceSubmission" class="Tests.AttendanceTest"/>
        <method signature="AttendanceTest.TC_004_VerifyAttendanceRecordedInDatabase()[pri:4, instance:Tests.AttendanceTest@232a7d73]" name="TC_004_VerifyAttendanceRecordedInDatabase" class="Tests.AttendanceTest"/>
        <method signature="CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed()[pri:1, instance:Tests.CallPlanTest@4372b9b6]" name="TC_001_Verify_Call_Plan_Module_Displayed" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_002_Verify_Sync_Button_Functionality()[pri:2, instance:Tests.CallPlanTest@4372b9b6]" name="TC_002_Verify_Sync_Button_Functionality" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_003_Verify_5_Minute_Sync_Process()[pri:3, instance:Tests.CallPlanTest@4372b9b6]" name="TC_003_Verify_5_Minute_Sync_Process" class="Tests.CallPlanTest"/>
        <method signature="CallPlanTest.TC_009_Verify_Call_Upload()[pri:5, instance:Tests.CallPlanTest@4372b9b6]" name="TC_009_Verify_Call_Upload" class="Tests.CallPlanTest"/>
        <method signature="DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed()[pri:1, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_001_VerifyDownloadCallsModuleIsDisplayed" class="Tests.DownloadcallsTest"/>
        <method signature="DownloadcallsTest.TC_002_VerifyCallsAreDownloaded()[pri:2, instance:Tests.DownloadcallsTest@1ecee32c]" name="TC_002_VerifyCallsAreDownloaded" class="Tests.DownloadcallsTest"/>
        <method signature="ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed()[pri:1, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC_001_Verify_ResourceCenter_Module_Displayed" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC002_VerifyPPTXFileDownloaded()[pri:2, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC002_VerifyPPTXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC003_VerifyMP4FileDownloaded()[pri:3, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC003_VerifyMP4FileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC004_VerifyPDFFileDownloaded()[pri:4, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC004_VerifyPDFFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC005_VerifyDOCXFileDownloaded()[pri:5, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC005_VerifyDOCXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC006_VerifyJPGFileDownloaded()[pri:6, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC006_VerifyJPGFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="ResourceCentreTest.TC007_VerifyXLSXFileDownloaded()[pri:7, instance:Tests.ResourceCentreTest@22ffa91a]" name="TC007_VerifyXLSXFileDownloaded" class="Tests.ResourceCentreTest"/>
        <method signature="VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed()[pri:1, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_001_VerifyVisitorLoginModuleDisplayed" class="Tests.VisitorLoginTest"/>
        <method signature="VisitorLoginTest.TC_015_Verify_Visitor_Upload()[pri:15, instance:Tests.VisitorLoginTest@4b41e4dd]" name="TC_015_Verify_Visitor_Upload" class="Tests.VisitorLoginTest"/>
        <method signature="LoginTest.TC_001_Verify_Login_With_Valid_Credentials()[pri:1, instance:Tests.LoginTest@63dd899]" name="TC_001_Verify_Login_With_Valid_Credentials" class="Tests.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-06-13T16:05:36 IST" name="Regression Tests" finished-at="2024-06-13T16:05:36 IST" duration-ms="184">
      <class name="Tests.ResourceCentreTest">
        <test-method signature="TC_001_Verify_ResourceCenter_Module_Displayed()[pri:1, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC_001_Verify_ResourceCenter_Module_Displayed" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Verify_ResourceCenter_Module_Displayed -->
        <test-method signature="TC002_VerifyPPTXFileDownloaded()[pri:2, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC002_VerifyPPTXFileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC002_VerifyPPTXFileDownloaded()[pri:2, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC002_VerifyPPTXFileDownloaded()[pri:2, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_VerifyPPTXFileDownloaded -->
        <test-method signature="TC003_VerifyMP4FileDownloaded()[pri:3, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC003_VerifyMP4FileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC003_VerifyMP4FileDownloaded()[pri:3, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC003_VerifyMP4FileDownloaded()[pri:3, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_VerifyMP4FileDownloaded -->
        <test-method signature="TC004_VerifyPDFFileDownloaded()[pri:4, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC004_VerifyPDFFileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC004_VerifyPDFFileDownloaded()[pri:4, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC004_VerifyPDFFileDownloaded()[pri:4, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_VerifyPDFFileDownloaded -->
        <test-method signature="TC005_VerifyDOCXFileDownloaded()[pri:5, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC005_VerifyDOCXFileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC005_VerifyDOCXFileDownloaded()[pri:5, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC005_VerifyDOCXFileDownloaded()[pri:5, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005_VerifyDOCXFileDownloaded -->
        <test-method signature="TC006_VerifyJPGFileDownloaded()[pri:6, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC006_VerifyJPGFileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC006_VerifyJPGFileDownloaded()[pri:6, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC006_VerifyJPGFileDownloaded()[pri:6, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC006_VerifyJPGFileDownloaded -->
        <test-method signature="TC007_VerifyXLSXFileDownloaded()[pri:7, instance:Tests.ResourceCentreTest@22ffa91a]" started-at="2024-06-13T16:05:36 IST" name="TC007_VerifyXLSXFileDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.ResourceCentreTest.TC_001_Verify_ResourceCenter_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourceCentreTest.TC007_VerifyXLSXFileDownloaded()[pri:7, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourceCentreTest.TC007_VerifyXLSXFileDownloaded()[pri:7, instance:Tests.ResourceCentreTest@22ffa91a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC007_VerifyXLSXFileDownloaded -->
      </class> <!-- Tests.ResourceCentreTest -->
      <class name="Tests.DownloadcallsTest">
        <test-method signature="TC_001_VerifyDownloadCallsModuleIsDisplayed()[pri:1, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_001_VerifyDownloadCallsModuleIsDisplayed" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_VerifyDownloadCallsModuleIsDisplayed -->
        <test-method signature="TC_002_VerifyCallsAreDownloaded()[pri:2, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_002_VerifyCallsAreDownloaded" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_002_VerifyCallsAreDownloaded()[pri:2, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_002_VerifyCallsAreDownloaded()[pri:2, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_VerifyCallsAreDownloaded -->
        <test-method signature="TC_003_VerifyDuplicateCallDownload()[pri:3, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_003_VerifyDuplicateCallDownload" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_003_VerifyDuplicateCallDownload()[pri:3, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_003_VerifyDuplicateCallDownload()[pri:3, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_VerifyDuplicateCallDownload -->
        <test-method signature="TC_004_VerifyInvalidTargetDownload()[pri:4, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_004_VerifyInvalidTargetDownload" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_004_VerifyInvalidTargetDownload()[pri:4, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_004_VerifyInvalidTargetDownload()[pri:4, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_VerifyInvalidTargetDownload -->
        <test-method signature="TC_005_VerifyRemoveButtonFunctionality()[pri:5, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_005_VerifyRemoveButtonFunctionality" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_005_VerifyRemoveButtonFunctionality()[pri:5, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_005_VerifyRemoveButtonFunctionality()[pri:5, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_VerifyRemoveButtonFunctionality -->
        <test-method signature="TC_006_VerifySubmitButtonWithoutAddingTarget()[pri:6, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_006_VerifySubmitButtonWithoutAddingTarget" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_006_VerifySubmitButtonWithoutAddingTarget()[pri:6, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_006_VerifySubmitButtonWithoutAddingTarget()[pri:6, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_006_VerifySubmitButtonWithoutAddingTarget -->
        <test-method signature="TC_007_VerifyTargetIDTextboxCharacterLimit()[pri:7, instance:Tests.DownloadcallsTest@1ecee32c]" started-at="2024-06-13T16:05:36 IST" name="TC_007_VerifyTargetIDTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.DownloadcallsTest.TC_001_VerifyDownloadCallsModuleIsDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DownloadcallsTest.TC_007_VerifyTargetIDTextboxCharacterLimit()[pri:7, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DownloadcallsTest.TC_007_VerifyTargetIDTextboxCharacterLimit()[pri:7, instance:Tests.DownloadcallsTest@1ecee32c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_007_VerifyTargetIDTextboxCharacterLimit -->
      </class> <!-- Tests.DownloadcallsTest -->
      <class name="Tests.AttendanceTest">
        <test-method signature="TC_001_VerifyAttendanceModuleDisplayed()[pri:1, instance:Tests.AttendanceTest@232a7d73]" started-at="2024-06-13T16:05:36 IST" name="TC_001_VerifyAttendanceModuleDisplayed" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_VerifyAttendanceModuleDisplayed -->
        <test-method signature="TC_002_VerifyAttendanceWithoutCapturingImage()[pri:2, instance:Tests.AttendanceTest@232a7d73]" started-at="2024-06-13T16:05:36 IST" name="TC_002_VerifyAttendanceWithoutCapturingImage" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.AttendanceTest.TC_001_VerifyAttendanceModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AttendanceTest.TC_002_VerifyAttendanceWithoutCapturingImage()[pri:2, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AttendanceTest.TC_002_VerifyAttendanceWithoutCapturingImage()[pri:2, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_VerifyAttendanceWithoutCapturingImage -->
        <test-method signature="TC_003_VerifyAttendanceSubmission()[pri:3, instance:Tests.AttendanceTest@232a7d73]" started-at="2024-06-13T16:05:36 IST" name="TC_003_VerifyAttendanceSubmission" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.AttendanceTest.TC_001_VerifyAttendanceModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AttendanceTest.TC_003_VerifyAttendanceSubmission()[pri:3, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AttendanceTest.TC_003_VerifyAttendanceSubmission()[pri:3, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_VerifyAttendanceSubmission -->
        <test-method signature="TC_004_VerifyAttendanceRecordedInDatabase()[pri:4, instance:Tests.AttendanceTest@232a7d73]" started-at="2024-06-13T16:05:36 IST" name="TC_004_VerifyAttendanceRecordedInDatabase" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.AttendanceTest.TC_003_VerifyAttendanceSubmission" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AttendanceTest.TC_004_VerifyAttendanceRecordedInDatabase()[pri:4, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AttendanceTest.TC_004_VerifyAttendanceRecordedInDatabase()[pri:4, instance:Tests.AttendanceTest@232a7d73] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_VerifyAttendanceRecordedInDatabase -->
      </class> <!-- Tests.AttendanceTest -->
      <class name="Tests.VisitorLoginTest">
        <test-method signature="TC_001_VerifyVisitorLoginModuleDisplayed()[pri:1, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_001_VerifyVisitorLoginModuleDisplayed" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_VerifyVisitorLoginModuleDisplayed -->
        <test-method signature="TC_002_VerifySubmitButtonWithoutEnteringFields()[pri:2, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_002_VerifySubmitButtonWithoutEnteringFields" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_002_VerifySubmitButtonWithoutEnteringFields()[pri:2, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_002_VerifySubmitButtonWithoutEnteringFields()[pri:2, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_VerifySubmitButtonWithoutEnteringFields -->
        <test-method signature="TC_003_VerifyVisitorEmpIDTextboxCharacterLimit()[pri:3, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_003_VerifyVisitorEmpIDTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_003_VerifyVisitorEmpIDTextboxCharacterLimit()[pri:3, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_003_VerifyVisitorEmpIDTextboxCharacterLimit()[pri:3, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_VerifyVisitorEmpIDTextboxCharacterLimit -->
        <test-method signature="TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters()[pri:4, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters()[pri:4, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters()[pri:4, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers()[pri:5, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers()[pri:5, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers()[pri:5, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers -->
        <test-method signature="TC_006_VerifyVisitorNameTextboxCharacterLimit()[pri:6, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_006_VerifyVisitorNameTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_006_VerifyVisitorNameTextboxCharacterLimit()[pri:6, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_006_VerifyVisitorNameTextboxCharacterLimit()[pri:6, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_006_VerifyVisitorNameTextboxCharacterLimit -->
        <test-method signature="TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters()[pri:7, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters()[pri:7, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters()[pri:7, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_008_VerifyVisitorNameTextboxAcceptsNumbers()[pri:8, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_008_VerifyVisitorNameTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_008_VerifyVisitorNameTextboxAcceptsNumbers()[pri:8, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_008_VerifyVisitorNameTextboxAcceptsNumbers()[pri:8, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_008_VerifyVisitorNameTextboxAcceptsNumbers -->
        <test-method signature="TC_009_VerifyDesignationTextboxCharacterLimit()[pri:9, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_009_VerifyDesignationTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_009_VerifyDesignationTextboxCharacterLimit()[pri:9, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_009_VerifyDesignationTextboxCharacterLimit()[pri:9, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_009_VerifyDesignationTextboxCharacterLimit -->
        <test-method signature="TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters()[pri:10, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters()[pri:10, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters()[pri:10, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_011_VerifyDesignationTextboxAcceptsNumbers()[pri:11, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_011_VerifyDesignationTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_011_VerifyDesignationTextboxAcceptsNumbers()[pri:11, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_011_VerifyDesignationTextboxAcceptsNumbers()[pri:11, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_011_VerifyDesignationTextboxAcceptsNumbers -->
        <test-method signature="TC_012_VerifyRemarksTextboxCharacterLimit()[pri:12, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_012_VerifyRemarksTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_012_VerifyRemarksTextboxCharacterLimit()[pri:12, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_012_VerifyRemarksTextboxCharacterLimit()[pri:12, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_012_VerifyRemarksTextboxCharacterLimit -->
        <test-method signature="TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters()[pri:13, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters()[pri:13, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters()[pri:13, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_014_Verify_RemarksTextboxAcceptsNumbers()[pri:14, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_014_Verify_RemarksTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_014_Verify_RemarksTextboxAcceptsNumbers()[pri:14, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_014_Verify_RemarksTextboxAcceptsNumbers()[pri:14, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_014_Verify_RemarksTextboxAcceptsNumbers -->
        <test-method signature="TC_015_Verify_Visitor_Upload()[pri:15, instance:Tests.VisitorLoginTest@4b41e4dd]" started-at="2024-06-13T16:05:36 IST" name="TC_015_Verify_Visitor_Upload" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.VisitorLoginTest.TC_001_VerifyVisitorLoginModuleDisplayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VisitorLoginTest.TC_015_Verify_Visitor_Upload()[pri:15, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VisitorLoginTest.TC_015_Verify_Visitor_Upload()[pri:15, instance:Tests.VisitorLoginTest@4b41e4dd] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_015_Verify_Visitor_Upload -->
      </class> <!-- Tests.VisitorLoginTest -->
      <class name="Tests.CallPlanTest">
        <test-method signature="TC_001_Verify_Call_Plan_Module_Displayed()[pri:1, instance:Tests.CallPlanTest@4372b9b6]" started-at="2024-06-13T16:05:36 IST" name="TC_001_Verify_Call_Plan_Module_Displayed" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Verify_Call_Plan_Module_Displayed -->
        <test-method signature="TC_002_Verify_Sync_Button_Functionality()[pri:2, instance:Tests.CallPlanTest@4372b9b6]" started-at="2024-06-13T16:05:36 IST" name="TC_002_Verify_Sync_Button_Functionality" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CallPlanTest.TC_002_Verify_Sync_Button_Functionality()[pri:2, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CallPlanTest.TC_002_Verify_Sync_Button_Functionality()[pri:2, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Verify_Sync_Button_Functionality -->
        <test-method signature="TC_003_Verify_5_Minute_Sync_Process()[pri:3, instance:Tests.CallPlanTest@4372b9b6]" started-at="2024-06-13T16:05:36 IST" name="TC_003_Verify_5_Minute_Sync_Process" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CallPlanTest.TC_003_Verify_5_Minute_Sync_Process()[pri:3, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CallPlanTest.TC_003_Verify_5_Minute_Sync_Process()[pri:3, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_Verify_5_Minute_Sync_Process -->
        <test-method signature="TC_005_Verify_Upload_Button_Without_Completing_Form()[pri:4, instance:Tests.CallPlanTest@4372b9b6]" started-at="2024-06-13T16:05:36 IST" name="TC_005_Verify_Upload_Button_Without_Completing_Form" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CallPlanTest.TC_005_Verify_Upload_Button_Without_Completing_Form()[pri:4, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CallPlanTest.TC_005_Verify_Upload_Button_Without_Completing_Form()[pri:4, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_Verify_Upload_Button_Without_Completing_Form -->
        <test-method signature="TC_009_Verify_Call_Upload()[pri:5, instance:Tests.CallPlanTest@4372b9b6]" started-at="2024-06-13T16:05:36 IST" name="TC_009_Verify_Call_Upload" finished-at="2024-06-13T16:05:36 IST" depends-on-methods="Tests.CallPlanTest.TC_001_Verify_Call_Plan_Module_Displayed" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CallPlanTest.TC_009_Verify_Call_Upload()[pri:5, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CallPlanTest.TC_009_Verify_Call_Upload()[pri:5, instance:Tests.CallPlanTest@4372b9b6] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_009_Verify_Call_Upload -->
      </class> <!-- Tests.CallPlanTest -->
      <class name="Tests.LoginTest">
        <test-method is-config="true" signature="StartApp()[pri:0, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:16 IST" name="StartApp" finished-at="2024-06-13T16:05:36 IST" duration-ms="20251" status="FAIL">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartApp -->
        <test-method signature="TC_001_Verify_Login_With_Valid_Credentials()[pri:1, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_001_Verify_Login_With_Valid_Credentials" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Verify_Login_With_Valid_Credentials -->
        <test-method signature="TC_002_Verify_Login_With_Invalid_Username()[pri:2, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_002_Verify_Login_With_Invalid_Username" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Verify_Login_With_Invalid_Username -->
        <test-method signature="TC_003_Verify_Login_With_Invalid_Password()[pri:3, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_003_Verify_Login_With_Invalid_Password" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_Verify_Login_With_Invalid_Password -->
        <test-method signature="TC_004_Verify_Login_With_Invalid_Project()[pri:4, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_004_Verify_Login_With_Invalid_Project" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_Verify_Login_With_Invalid_Project -->
        <test-method signature="TC_005_Verify_Login_With_Invalid_Mobile_Number()[pri:5, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_005_Verify_Login_With_Invalid_Mobile_Number" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_Verify_Login_With_Invalid_Mobile_Number -->
        <test-method signature="TC_006_Verify_Login_Without_Entering_Username()[pri:6, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_006_Verify_Login_Without_Entering_Username" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_006_Verify_Login_Without_Entering_Username -->
        <test-method signature="TC_007_Verify_Login_Without_Entering_Password()[pri:7, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_007_Verify_Login_Without_Entering_Password" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_007_Verify_Login_Without_Entering_Password -->
        <test-method signature="TC_008_Verify_Login_Without_Entering_Project()[pri:8, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_008_Verify_Login_Without_Entering_Project" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_008_Verify_Login_Without_Entering_Project -->
        <test-method signature="TC_009_Verify_Login_Without_Entering_Mobile_Number()[pri:9, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_009_Verify_Login_Without_Entering_Mobile_Number" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_009_Verify_Login_Without_Entering_Mobile_Number -->
        <test-method signature="TC_010_Verify_UsernameTextboxCharacterLimit()[pri:10, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_010_Verify_UsernameTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_010_Verify_UsernameTextboxCharacterLimit -->
        <test-method signature="TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters()[pri:11, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_011_Verify_UsernameTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_012_Verify_UsernameTextboxAcceptsNumbers()[pri:12, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_012_Verify_UsernameTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_012_Verify_UsernameTextboxAcceptsNumbers -->
        <test-method signature="TC_013_Verify_PasswordTextboxCharacterLimit()[pri:13, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_013_Verify_PasswordTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_013_Verify_PasswordTextboxCharacterLimit -->
        <test-method signature="TC_014_Verify_ProjectTextboxCharacterLimit()[pri:14, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_014_Verify_ProjectTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_014_Verify_ProjectTextboxCharacterLimit -->
        <test-method signature="TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters()[pri:15, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_015_Verify_ProjectTextboxAcceptsSpecialCharacters -->
        <test-method signature="TC_016_Verify_ProjectTextboxAcceptsNumbers()[pri:16, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_016_Verify_ProjectTextboxAcceptsNumbers" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_016_Verify_ProjectTextboxAcceptsNumbers -->
        <test-method signature="TC_017_Verify_MobileNumberTextboxCharacterLimit()[pri:17, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="TC_017_Verify_MobileNumberTextboxCharacterLimit" finished-at="2024-06-13T16:05:36 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
            <message>
              <![CDATA[The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter

]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Ezhil Rj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1] 
Process output: [35m[Appium][39m Welcome to Appium v2.5.4
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Ezhil Rj\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Requiring driver at C:\Users\Ezhil Rj\.appium\node_modules\appium-uiautomator2-driver\build\index.js
reusing global emitter


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:187)
at Base.TestSetup.StartApp(TestSetup.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Tests.Main.main(Main.java:34)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20006 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:152)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:174)
... 16 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_017_Verify_MobileNumberTextboxCharacterLimit -->
        <test-method is-config="true" signature="tearDownApp()[pri:0, instance:Tests.LoginTest@63dd899]" started-at="2024-06-13T16:05:36 IST" name="tearDownApp" finished-at="2024-06-13T16:05:48 IST" duration-ms="11525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownApp -->
      </class> <!-- Tests.LoginTest -->
    </test> <!-- Regression Tests -->
  </suite> <!-- Regression Suite -->
</testng-results>
